[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Computerdores"
name = "BetterTerminal"
description = "A Mod to add Auto Completion and Command History to the Terminal."
websiteUrl = "https://github.com/Computerdores/BetterTerminal"
containsNsfwContent = false

[package.dependencies]
# https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/
BepInEx-BepInExPack = "5.4.2100"
Computerdores-AdvancedTerminalAPI = "2.0.9"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "Template/bin/Template.dll"
target = "BepInEx/plugins/Template.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
lethal-company = ["bepinex", "mods", "client-side"]
